const ProjectDetails = {
  iNotepad: [
    "import iNotepad from 'me❤️✨';",
    "// import './iNotepad.css';  // Link to your CSS file",
    "const iNotepad = () => {",
    "  return (",
    "    <div>",
    "      <h1 className='heading'>",
    "       iNotepad is a modern notes management app enabling users to add, edit, and display their notes.",
    "       Built with React and Express, it focuses on simplicity, efficiency, and user-friendliness.",
    "       Secure authentication is implemented using JSON Web Tokens (JWT).",
    "     </h1>",
    "     <a href='https://inotepadv1.netlify.app/' target='_blank'>Live Demo</a>", // Inline CSS
    "     <h4 className='technologies'>",
    "      Technologies Used:",
    "        • Frontend: React, Axios, Tailwind, Bootstrap.",
    "        • Backend: Express.js, MongoDB, JSON Web Tokens (JWT).",
    "      Key Features:",
    "        • Add, edit, and display notes effortlessly.",
    "        • Responsive design with a customized navbar.",
    "        • Secure authentication with JWT.",
    "     </h4>",
    "    </div>",
    "  );",
    "};",
    "export default to you 😂😂;",
  ],
  iNotepadLink: ["https://inotepadv1.netlify.app/"],
  Amritam: [
    "import Amritam from 'me❤️✨';",
    "// import './Amritam.css'; ",
    "interface ProjectDetails {",
    "   title: string;",
    "   description: string;",
    "   LiveLink: string;",
    "   technologies: string[];",
    "   features: string[];",
    "}",
    "const Amritam: React.FC<ProjectDetails> = () => {",
    "  return (",
    "    <div>",
    "      <h1 className='heading'>",
    "       Amritam is a website focused on reintroducing natural and organic products into kitchens",
    "       emphasizing health, wellness, and sustainability. To enhance user experience, I created a ",
    "       user-friendly UI for the login and sign-up pages of the Amritam website. These pages provide",
    "       a seamless entry point for users to explore and engage with the brand's offerings.",
    "     </h1>",
    "     <a href='https://amritam.vercel.app/' target='_blank'>Live Demo</a>",
    "     <h4 className='technologies'>",
    "      Technologies Used:",
    "        • Frontend: React, TypeScript, Tailwind CSS.",
    "        • Backend: Node.js ,MongoDB, JavaScript.",
    "      Key Features:",
    "        • Clean, modern UI with a focus on the brand’s values.",
    "        • Responsive design for seamless experience across devices.",
    "     </h4>",
    "    </div>",
    "  );",
    "};",
    "export default to you 😂😂;",
  ],
  AmritamLink: ["https://amritam.vercel.app/"],
  clerktemplate: [
    "import ClerkTemplate from 'me❤️✨';",
    "// import './ClerkTemplate.css';",
    "const ClerkTemplate = () => {",
    "  return (",
    "    <div>",
    "      <h1 className='heading'>",
    "      ClerkTemplate is a customizable and modern template designed to integrate user authentication",
    "      seamlessly into websites. Built with **Clerk**, this template allows developers to quickly add ",
    "      functionality with minimal effort.Its responsive and clean design provides an excellent user  ",
    "      experience across all devices.",
    "     </h1>",
    "     <a href='https://clerk-nextjs-mongodb-zeta.vercel.app/' target='_blank'>Live Demo</a>",
    "     <h4 className='technologies'>",
    "      Technologies Used:",
    "        • Frontend: Nextjs, Tailwind CSS, and Bootstrap.",
    "        • Backend: MongoDB",
    "      Key Features:",
    "        • Fully responsive design for all screen sizes.",
    "        • Clean and modern layout with minimalistic styling.",
    "        • Easy to customize and integrate with other components.",
    "     </h4>",
    "    </div>",
    "  );",
    "};",
    "export default to you 😂😂;",
  ],
  clerktemplateLink: ["https://clerk-nextjs-mongodb-zeta.vercel.app/"],
  eBookHaven: [
    "import eBookHaven from 'me❤️✨';",
    "// import './eBookHaven.css'; ",
    "const eBookHaven = () => {",
    "  return (",
    "    <div>",
    "      <h1 className='heading'>",
    "       eBook Haven is an online platform designed to provide users with a vast collection of eBooks,",
    "       making it easy to access, read, and organize digital books. The platform allows users to",
    "       browse, search, and download their favorite books seamlessly.",
    "       eBook Haven is built with a focus on simplicity, speed, and a smooth reading experience.",
    "     </h1>",
    "     <a href='https://ebookhaven.netlify.app/' target='_blank'>Live Demo</a>",
    "     <h4 className='technologies'>",
    "      Technologies Used:",
    "        • Frontend: React, Bootstrap, Tailwind CSS.",
    "        • Backend: Node.js, Express.js, MongoDB (for handling eBook data).",
    "      Key Features:",
    "        • Browse and search a wide range of eBooks.",
    "        • Smooth and responsive design for an optimal reading experience.",
    "        • Easy to use with features like bookmark management and book preview.",
    "     </h4>",
    "    </div>",
    "  );",
    "};",
    "export default to you 😂😂;",
  ],
  eBookHavenLink: ["https://ebookhaven.netlify.app/"],
  myPortfolio: [
    ".about{",
    " The VSCode-Themed Portfolio is a personal portfolio website designed to  ",
    " replicate the look and feel of the popular Visual Studio Code editor.",
    "}",
    ".overview{",
    "  The portfolio includes a homepage, an about me section, projects showcase,",
    "  skills section, a experience section and a contact form. Each section is ",
    "  styled to mimic the interface of VSCode, providing users with a smooth and",
    "  familiar browsing experience. The idea behind the project was to create a ",
    "  portfolio that not only showcases technical skills but also provides a ",
    "  personalized user interface (UI) experience, resembling an integrated ",
    "  development environment (IDE).",
    "}",
    ".features{",
    "  VSCode-like Theme:   Dark.",
    "  Syntax Highlighting: Display code with proper syntax styling.",
    "  Sidebar Navigation:  Easy access to sections like About, Projects, Skills.",
    "  Responsive Design:   Seamless experience across devices.",
    "  Minimalist UI:       Clean, modern design with smooth animations.",
    "}",
    ".technologies-used{",
    "  Nextjs",
    "  React",
    "  CSS",
    "  javaScript",
    "  Redux Toolkit",
    "  Tailwind css",
    "}",
  ],
  ReferralShala: [
    "import ReferralShala from 'me❤️✨';",
    "// import './ReferralShala.css'; ",
    "const ReferralShala = () => {",
    "  return (",
    "    <div>",
    "      <h1 className='heading'>",
    "       ReferralShala is revolutionizing job referrals by connecting employers and candidates seamlessly.",
    "       Built with Next.js, Prisma, and PostgreSQL, it ensures efficiency and a smooth user experience.",
    "       Secure authentication is integrated using Clerk, enhancing user trust and privacy.",
    "     </h1>",
    "     <a href='https://referralshala.vercel.app/' target='_blank'>Live Demo</a>", // Inline CSS
    "     <h4 className='technologies'>",
    "      Technologies Used:",
    "        • Frontend: Next.js, JavaScript, CSS.",
    "        • Backend: Prisma, Neon, PostgreSQL, Supabase, Express.js.",
    "        • Authentication: Clerk.",
    "        • Email Services: Nodemailer.",
    "      Key Features:",
    "        • Secure login and user authentication with Clerk.",
    "        • Intuitive dashboards for managing job postings, applications, and profiles.",
    "        • Real-time data synchronization via RESTful APIs.",
    "        • Optimized database architecture with Prisma & PostgreSQL, reducing query response time by 20%.",
    "        • Automated email notifications via Nodemailer for application updates and referrals.",
    "     </h4>",
    "      <p className='mission'>",
    "        At ReferralShala, we believe everyone deserves the opportunity to reach their full potential.",
    "        Finding the right job or internship should be a journey of growth, not a struggle.",
    "        Our mission is to bridge the gap between talent and opportunities with tailored referrals,",
    "        helping you navigate the job market with confidence.",
    "      </p>",
    "    </div>",
    "  );",
    "};",
    "export default to you 😂😂;",
  ],
  ReferralShalaLink: ["https://referralshala.vercel.app/"],

  CloudHive: [
    "import CloudHive from 'me☁️🧠✨';",
    "// import './CloudHive.css';",
    "const CloudHive = () => {",
    "  return (",
    "    <div>",
    "      <h1 className='heading'>",
    "        CloudHive is a next-gen cloud storage aggregator designed to merge multiple Google Drive accounts into one seamless interface.",
    "        Built with Next.js, TypeScript, and Firebase, it enables real-time file browsing, uploads, and multi-account sync.",
    "        MongoDB handles OAuth tokens securely, while Redis caching boosts performance by minimizing redundant API calls.",
    "      </h1>",
    "      <a href='https://cloud-hive-app.vercel.app/' target='_blank'>Live Demo</a>",
    "      <h4 className='technologies'>",
    "        Technologies Used:",
    "          • Frontend: Next.js, TypeScript, Tailwind CSS.",
    "          • Backend: API Routes (Node.js), Cron Jobs.",
    "          • Authentication: Firebase (Google OAuth, Email/Password).",
    "          • Database: MongoDB.",
    "          • Caching: Redis.",
    "          • Cloud APIs: Google Drive API (10+ accounts per user).",
    "        Key Features:",
    "          • Unified dashboard for browsing and uploading across multiple Google Drive accounts.",
    "          • Secure session handling via Firebase session cookies.",
    "          • Responsive UI with Tailwind CSS for seamless cross-device experience.",
    "          • Redis-powered caching system that reduces file fetch latency by 70%.",
    "          • Daily cron jobs to refresh tokens and sync metadata automatically.",
    "      </h4>",
    "      <p className='mission'>",
    "        CloudHive was built to simplify the chaos of scattered cloud accounts.",
    "        Our mission is to bring order, visibility, and efficiency to how users interact with cloud storage —",
    "        helping them stay productive and in control of their data.",
    "      </p>",
    "    </div>",
    "  );",
    "};",
    "export default to you ☁️🚀;",
  ],
  CloudHiveLink: ["https://cloud-hive-app.vercel.app/"],
};

export default ProjectDetails;
