const ProjectDetails = {
    iNotepad: [
      "import iNotepad from 'me❤️✨';",
      "// import './iNotepad.css';  // Link to your CSS file",
      "const iNotepad = () => {",
      "  return (",
      "    <div>",
      "      <h1 className='heading'>",
      "       iNotepad is a modern notes management app enabling users to add, edit, and display their notes.",
      "       Built with React and Express, it focuses on simplicity, efficiency, and user-friendliness.",
      "       Secure authentication is implemented using JSON Web Tokens (JWT).",
      "     </h1>",
      "     <a href='https://inotepadv1.netlify.app/' target='_blank'>Live Demo</a>", // Inline CSS
      "     <h4 className='technologies'>",
      "      Technologies Used:",
      "        • Frontend: React, Axios, Tailwind, Bootstrap.",
      "        • Backend: Express.js, MongoDB, JSON Web Tokens (JWT).",
      "      Key Features:",
      "        • Add, edit, and display notes effortlessly.",
      "        • Responsive design with a customized navbar.",
      "        • Secure authentication with JWT.",
      "     </h4>",
      "    </div>",
      "  );",
      "};",
      "export default to you 😂😂;"
    ],
    iNotepadLink:["https://inotepadv1.netlify.app/"],
    Amritam: [
      "import Amritam from 'me❤️✨';",
      "// import './Amritam.css';  // Link to your CSS file",
      "interface ProjectDetails {",
      "   title: string;",
      "   description: string;",
      "   LiveLink: string;",
      "   technologies: string[];",
      "   features: string[];",
      "}",
      "const Amritam: React.FC<ProjectDetails> = () => {",
      "  return (",
      "    <div>",
      "      <h1 className='heading'>",
      "       Amritam is a website focused on reintroducing natural and organic products into kitchens",
      "       emphasizing health, wellness, and sustainability. To enhance user experience, I created a ",
      "       user-friendly UI for the login and sign-up pages of the Amritam website. These pages provide",
      "       a seamless entry point for users to explore and engage with the brand's offerings.",
      "     </h1>",
      "     <a href='https://amritam.vercel.app/' target='_blank'>Live Demo</a>",
      "     <h4 className='technologies'>",
      "      Technologies Used:",
      "        • Frontend: React, TypeScript, Tailwind CSS.",
      "        • Backend: Node.js ,MongoDB, JavaScript.",
      "      Key Features:",
      "        • Clean, modern UI with a focus on the brand’s values.",
      "        • Responsive design for seamless experience across devices.",
      "     </h4>",
      "    </div>",
      "  );",
      "};",
      "export default to you 😂😂;"
    ],
    AmritamLink:["https://amritam.vercel.app/"],
    clerktemplate: [
      "import ClerkTemplate from 'me❤️✨';",
      "// import './ClerkTemplate.css';  // Link to your CSS file",
      "const ClerkTemplate = () => {",
      "  return (",
      "    <div>",
      "      <h1 className='heading'>",
      "      ClerkTemplate is a customizable and modern template designed to integrate user authentication",
      "      seamlessly into websites. Built with **Clerk**, this template allows developers to quickly add ",
      "      seamlessly into websites. Built with **Clerk**, this template allows developers to quickly add ",
      "      Its responsive and clean design provides an excellent user experience across all devices.",
      "     </h1>",
      "     <a href='https://clerk-nextjs-mongodb-zeta.vercel.app/' target='_blank'>Live Demo</a>",
      "     <h4 className='technologies'>",
      "      Technologies Used:",
      "        • Frontend: Nextjs, Tailwind CSS, and Bootstrap.",
      "        • Backend: MongoDB",
      "      Key Features:",
      "        • Fully responsive design for all screen sizes.",
      "        • Clean and modern layout with minimalistic styling.",
      "        • Easy to customize and integrate with other components.",
      "     </h4>",
      "    </div>",
      "  );",
      "};",
      "export default to you 😂😂;"
    ],
    clerktemplateLink:["https://clerk-nextjs-mongodb-zeta.vercel.app/"],
    eBookHaven: [
      "import eBookHaven from 'me❤️✨';",
      "// import './eBookHaven.css';  // Link to your CSS file",
      "const eBookHaven = () => {",
      "  return (",
      "    <div>",
      "      <h1 className='heading'>",
      "       eBook Haven is an online platform designed to provide users with a vast collection of eBooks,",
      "       making it easy to access, read, and organize digital books. The platform allows users to",
      "       browse, search, and download their favorite books seamlessly.",
      "       eBook Haven is built with a focus on simplicity, speed, and a smooth reading experience.",
      "     </h1>",
      "     <a href='https://ebookhaven.netlify.app/' target='_blank'>Live Demo</a>", 
      "     <h4 className='technologies'>",
      "      Technologies Used:",
      "        • Frontend: React, Bootstrap, Tailwind CSS.",
      "        • Backend: Node.js, Express.js, MongoDB (for handling eBook data).",
      "      Key Features:",
      "        • Browse and search a wide range of eBooks.",
      "        • Smooth and responsive design for an optimal reading experience.",
      "        • Easy to use with features like bookmark management and book preview.",
      "     </h4>",
      "    </div>",
      "  );",
      "};",
      "export default eBookHaven 😂😂;"
    ],
    eBookHavenLink:["https://ebookhaven.netlify.app/"],
    myPortfolio:[
      ".about{",
      " The VSCode-Themed Portfolio is a personal portfolio website designed to  ",
      " replicate the look and feel of the popular Visual Studio Code editor.",
      "}",
      ".overview{",
      "  The portfolio includes a homepage, an about me section, projects showcase,",
      "  skills section, a experience section and a contact form. Each section is ",
      "  styled to mimic the interface of VSCode, providing users with a smooth and",
      "  familiar browsing experience. The idea behind the project was to create a ",
      "  portfolio that not only showcases technical skills but also provides a ",
      "  personalized user interface (UI) experience, resembling an integrated ",
      "  development environment (IDE).",
      "}",
      ".features{",
      "  VSCode-like Theme:   Dark.",
      "  Syntax Highlighting: Display code with proper syntax styling.",
      "  Sidebar Navigation:  Easy access to sections like About, Projects, Skills.",
      "  Responsive Design:   Seamless experience across devices.",
      "  Minimalist UI:       Clean, modern design with smooth animations.",
      "}",
      ".technologies-used{",
      "  Nextjs",
      "  React",
      "  CSS",
      "  javaScript",
      "  Redux Toolkit",
      "  Tailwind css",
      "}",
    ],

  };

  
  export default ProjectDetails;